export const ENVIRONMENT = process.env.ENVIRONMENT || 'dev'
export const PROJECT_NAME = process.env.PROJECT_NAME || 'testing'
export const HOSTED_ZONE_ID = process.env.HOSTED_ZONE_ID || ''
export const HOSTED_ZONE_NAME = process.env.HOSTED_ZONE_NAME || ''
export const AWS_REGION = process.env.AWS_REGION || 'us-east-1'
